In [1]:
import pandas as pd

In [2]:
import os
os.chdir(r"C:\Users\PREM\OneDrive\Desktop\Internship_Project\raw")

In [3]:
df = pd.read_excel('Dataset.xlsx')
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [5]:
df.describe().round()

                      Date  Quantity  UnitPrice  ItemsInCart  TotalPrice
count                 1200    1200.0     1200.0       1200.0      1200.0
mean   2024-03-22 16:58:48       3.0      356.0          5.0      1054.0
min    2023-01-01 00:00:00       1.0       11.0          1.0        11.0
25%    2023-08-03 18:00:00       2.0      186.0          4.0       411.0
50%    2024-03-23 00:00:00       3.0      364.0          5.0       824.0
75%    2024-11-08 12:00:00       4.0      522.0          7.0      1578.0
max    2025-06-30 00:00:00       5.0      700.0         10.0      3456.0
std                    NaN       1.0      197.0          2.0       820.0

In [6]:
df.isnull().sum()/len(df)*100

OrderID             0.00
Date                0.00
CustomerID          0.00
Product             0.00
Quantity            0.00
UnitPrice           0.00
ShippingAddress     0.00
PaymentMethod       0.00
OrderStatus         0.00
TrackingNumber      0.00
ItemsInCart         0.00
CouponCode         25.75
ReferralSource      0.00
TotalPrice          0.00
dtype: float64

In [7]:
df.shape

(1200, 14)

In [8]:
df[df.duplicated()].shape

(0, 14)

In [9]:
df['CustomerID'].value_counts()

CustomerID
C38840    2
C14847    2
C21191    2
C94569    2
C46651    2
         ..
C99217    1
C30010    1
C70148    1
C39906    1
C57502    1
Name: count, Length: 1189, dtype: int64

In [10]:
df[df['CustomerID'] == 'C38840']

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
266,ORD200266,2024-06-08,C38840,Chair,4,583.07,589 Main St,Credit Card,Cancelled,TRK48484633,6,FREESHIP,Referral,2332.28
1122,ORD201122,2023-06-07,C38840,Monitor,5,678.19,766 Main St,Online,Returned,TRK32496970,8,NaN,Facebook,3390.95

In [11]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(df[col].value_counts())
        print('-'*50)

Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64
--------------------------------------------------
Quantity
1    255
4    251
2    240
3    237
5    217
Name: count, dtype: int64
--------------------------------------------------
PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64
--------------------------------------------------
OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64
--------------------------------------------------
ItemsInCart
5     191
6     190
4     163
7     151
8     129
3     123
9      79
2      78
1      50
10     46
Name: count, dtype: int64
--------------------------------------------------
CouponCode
FREESHIP    313
WINTER15    292
SAVE10      286
Name: count, dtype: int64
--------------------------------------------------
ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64
--------------------------------------------------

In [12]:
df.shape

(1200, 14)

In [13]:
df.dropna(subset=['CouponCode'],inplace=True)

In [14]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [15]:
df.shape

(891, 14)

In [16]:
df[df.duplicated()].shape

(0, 14)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df['CustomerID'].value_counts()

CustomerID
C56969    2
C46651    2
C21191    2
C97593    2
C91155    2
         ..
C28893    1
C97774    1
C11657    1
C85993    1
C57502    1
Name: count, Length: 886, dtype: int64

In [19]:
df.drop_duplicates(subset=['CustomerID'],keep='first',inplace=True)
df['CustomerID'].value_counts()

CustomerID
C72649    1
C24769    1
C33313    1
C20861    1
C26364    1
         ..
C28893    1
C97774    1
C11657    1
C85993    1
C57502    1
Name: count, Length: 886, dtype: int64

In [20]:
df.shape

(886, 14)

In [21]:
print(df['Date'].dt.strftime('%Y-%m-%d').head())

0    2023-01-04
1    2024-08-23
2    2024-02-27
3    2023-10-15
4    2025-05-08
Name: Date, dtype: object

In [22]:
df['UnitPrice'] = df['UnitPrice'].round(2)
df['TotalPrice'] = df['TotalPrice'].round(2)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 886 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          886 non-null    object
 1   Date             886 non-null    datetime64[ns]
 2   CustomerID       886 non-null    object
 3   Product          886 non-null    object
 4   Quantity         886 non-null    int64
 5   UnitPrice        886 non-null    float64
 6   ShippingAddress  886 non-null    object
 7   PaymentMethod    886 non-null    object
 8   OrderStatus      886 non-null    object
 9   TrackingNumber   886 non-null    object
 10  ItemsInCart      886 non-null    int64
 11  CouponCode       886 non-null    object
 12  ReferralSource   886 non-null    object
 13  TotalPrice       886 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 103.8+ KB

In [24]:
df.to_excel(r"C:\Users\PREM\OneDrive\Desktop\Internship_Project\processed\cleaned_dataset.xlsx", index=False)
print("Saved")

Saved